container-mgmt/dedicated-portal

pkg/signals/signal.go

@jhernand @nimrodshn please review

Extract signals from autoheal to pkg/signals

---

cmd/customers-webserver/cluster.go
cmd/customers-webserver/cluster_handler.go
cmd/customers-webserver/utils.go

This is a followup to PR #10, addressing some review comments.

customers webserver: code cleanup

---

Gopkg.lock
Gopkg.toml
cmd/clusters-service/clusters_service.go
cmd/clusters-service/main.go
cmd/clusters-service/notifier.go
cmd/clusters-service/openapi.yaml
cmd/clusters-service/server.go
images/messaging-service/etc/broker.xml

Replaces https://github.com/container-mgmt/dedicated-portal/pull/13

Add clusters service

---

cmd/customers-service/customer-service.yaml

cc: @jhernand @elad661 @moolitayer

Fix openapi doc errors to appease swagger UI linter.

---

Jenkinsfile
build.py
template.sh
template.yml

This patch adds an initial `Jenkinsfile` that can be used to build and deploy the application to an _OpenShift_ cluster.

Add Jenkinsfile

---

README.adoc

This patch does the following minor changes in the `README.adoc` file of the project:
- Uses `[source]` for all the code blocks.
- Replaces _OpenShirt_ with _OpenShift_.
- Fixes the defult version of the images: it used to be `0.0.0` but it is `latest` now.

Minor cleanups in the 'README' file

---

Gopkg.lock
cmd/customers-service/customer.go
cmd/customers-service/customers-service.yaml
cmd/customers-service/customers_list.go
cmd/customers-service/customers_service.go
cmd/customers-service/etcd_customers_service.go
cmd/customers-service/handlers.go
cmd/customers-service/server.go

~~Please, **Do not merge**,~~ this is just for transparency so that everyone can see the direction I am taking.
I tried to follow (more or less) @moolitayer's architecture.
cc: @jhernand  @moolitayer

Initial implementation of customers-service REST api

---

cmd/customers-service/customers_service.go
cmd/customers-service/etcd_customers_service.go

Some much needed comments.
@jhernand @moolitayer

Adding comments to customers service interface

---

cmd/customers-service/etcd_customers_service.go
cmd/customers-service/handlers.go

customers-service: connect handlers to the service

---

README.adoc
hack/cluster-up.sh
template.sh

@moolitayer @jhernand please review

Parametrize template.sh, set DOMAIN automatically from cluster-up.sh

---

template.yml

postgresql can be accessed using:
```
oc get pods
oc rsh -c postgresql <pod>
PGPASSWORD=redhat123 psql -h localhost
```

Add a pgsql container

---

.travis.yml
Makefile
build.py
cmd/clusters-service/clusters_service.go
cmd/clusters-service/notifier.go
cmd/clusters-service/server.go
cmd/customers-service/customers_service.go
cmd/customers-service/etcd_customers_service.go

Add lint and misspell to travis

Add lint and misspell to travis

---

cmd/customers-service/etcd_customers_service.go
cmd/customers-service/etcd_customers_service_test.go

cc: @jhernand  @moolitayer 
This depends on #38 where there is a patch for a small bug.

Adding integration tests for etcd customers service

---

cmd/customers-service/server.go

We lost some linting issues in https://github.com/container-mgmt/dedicated-portal/pull/48 due to a rebase, This PR re-do the lost fixes.

Lint and spelling fixes

---

build.py

The project from where the `build.py` script was initially copied needed to generate the Dockerfiles from templates. That isn't used in this project, so this patch removes that code.

Remove support from templates from `build.py`

---

cmd/customers-service/README.adoc
cmd/customers-service/handlers.go
cmd/customers-service/server.go

Refactored the http request handler  in order  to add support for both `/customer` and `/customers?page=X&size=Y`.
In addition, this PR adds a readme file with detailed instructions for interacting with the customers-service.
cc: @cben @jhernand

Refactoring request handlers and adding readme

---

cmd/customers-service/handlers.go
cmd/customers-service/sql_customers_service.go

This pull request fixes a couple of minor issues that make the customers service fail when there are no customers in the database.

Minor customer service fixes

---

cmd/clusters-service/clusters_service.go
cmd/clusters-service/server.go

This pull request fixes a couple of minor issues in the clusters service that result in generating incorrect JSON and incorrect content type headers.

Minor clusters service fixes

---

cmd/customers-service/customers-service.yaml
cmd/customers-service/swagger/README.adoc
cmd/customers-service/swagger/swagger_test.py

We are using `openapi` files, this PR adds the ability to check this files.
First step in solving: https://github.com/container-mgmt/dedicated-portal/issues/15

Add a swagger codegen test

---

cmd/clusters-service/handlers.go
cmd/clusters-service/main.go
cmd/clusters-service/server.go

1. Adds cobra for cli managment.
2. Extract conn handlers form server.go into a seperate file.

clusters service: Adding cobra for cli and some refactoring

---

Makefile
template.yml

Makefile - fix typo in the images prefix
template.yml - Need to add parameter after merging https://github.com/container-mgmt/dedicated-portal/pull/82

Fix Makefile and template.yml

---

Gopkg.lock
Gopkg.toml
cmd/customers-service/handlers.go
cmd/customers-service/jwtcert/jwtcert.go
cmd/customers-service/server.go
template.yml

Add Bearer authentication to the customer service.
**Terminal dump**
Server
```
$ customers-service serve
I0718 10:32:13.081950    9566 server.go:109] Starting customers-service server at 0.0.0.0:8000.
::1 - - [18/Jul/2018:10:32:20 +0300] "GET /api/customers_mgmt/v1/customers HTTP/1.1" 401 39
::1 - - [18/Jul/2018:10:32:31 +0300] "GET /api/customers_mgmt/v1/customers HTTP/1.1" 401 45
::1 - - [18/Jul/2018:10:45:16 +0300] "GET /api/customers_mgmt/v1/customers HTTP/1.1" 400 90
```
Client
No token
```
$ curl -s http://localhost:8000/api/customers_mgmt/v1/customers
{"error":"Required authorization token not found"}
```
Bad token
```
$ curl -s http://localhost:8000/api/customers_mgmt/v1/customers -H "authorization: Bearer BADTOKEN"
{"error":"token contains an invalid number of …
```

Check token

---

template.yml

Fix typo from #83
args in template need equal sign

Add missing equal sign

---

cmd/customers-service/server.go

@yaacov please review (and wait for Travis to be green)

Re-add imports that were accidentally removed

---

cmd/clusters-service/server.go
cmd/customers-service/models/customers.sql
cmd/customers-service/server.go
cmd/customers-service/service/demo_customers_service.go
images/customers-service/Dockerfile
images/customers-service/migrations/1530102671_create_schema.down.sql
images/customers-service/migrations/1530102671_create_schema.up.sql
pkg/sql/schema.go
template.yml

Use migrations in customers server.

Use migrations

---

template.yml

PR #101 broke deployment - this patch fixes the broken changes.
cc: @jhernand @yaacov @zgalor

clusters-service: switch from env vars to flags broke deployment

---

cmd/clusters-service/README.adoc
cmd/clusters-service/cluster_provisioner.go
cmd/clusters-service/clusters_service.go
images/clusters-service/migrations/1530102892_add_cluster_details.down.sql
images/clusters-service/migrations/1530102892_add_cluster_details.up.sql
pkg/api/cluster_types.go

This PR adds the region field, updates it and the DB and uses it in cluster operator provisioner

Add Cluster Region field to API and DB

---

cmd/customers-service/handlers.go
cmd/customers-service/server.go
cmd/customers-service/service/demo_customers_service.go
cmd/customers-service/service/sql_customers_service.go
cmd/customers-service/service/sql_customers_service_test.go

Note: **Still haven't tested this yet, please do not merge.** 
This fixes some buggy and irrelevant code in customers-service.
cc: @elad661 @yaacov @jhernand

Refactor some code in customers service

---

Makefile
cmd/clusters-service/clusters_service.go
hack/verify.sh

Remove `goimports` check, fix usage of go lint, fix fmt and linting errors where found.

Remove goimports check

---

cmd/clusters-service/server.go
cmd/customers-service/server.go

Currently the migration  path is wrong, this PR fixes that.

Fix sql migrations path prefix

---

pkg/auth/auth.go

Currently we verify the token presented by the caller assuming that there will be only one token singing key published by the identity provider.
This PR use the tokens `kid` header to get the correct key from the  identity providers `certs` file.

Use correct token

---

README.adoc

Add more info about using the `cluster-up` hack.

More verbose hack info

---

.gitignore

Update gitignore to ignore [clusters/customers]/data

---

Makefile

@nimrodshn @yaacov @oourfali please review

Make: helpful error when you don't have mercurial

---

cmd/clusters-service/server.go
cmd/customers-service/server.go
template.yml

Protect services communication with TLS

Protect services communication with TLS

---

cmd/clusters-service/cluster_provisioner.go

Following naming conventions in Go, this PR changes the receiver name in `ClusterOperatorProvisioner` from `provisioner` to `p`. 
plus, removes one redundant alias. 
cc: @cben @jhernand @zgalor @yaacov

Changing receiver name at cluster_provisioner.go

---

Makefile
README.adoc
template.yml

Protect postgresql communication with TLS

Protect postgresql communication with TLS
