cmd/customers-service/customer-service.yaml
This PR adds the OpenAPI (v3.0.0) document to the customers service package.
This document describes in a clear and concise language the API specifications for the `Customers Service`.
cc: @jhernand, @moolitayer
=> Add OpenAPI document to customers service

build
Catching generic Exception this way causes Python to not print
the backtrace, making errors more difficult to debug.
Since all the exception handler was doing is printing the exception
message, it's much better to just remove it entirely.
=> build script: don't mask exceptions

build
@jhernand I think the `say()` function is redundant, Python has this functionality built in. Removing it makes the script slightly more readable :)
=> build script: don't reimplement the python print function

cmd/customers-service/customer-service.yaml
This patch fixes a typo in the _OpenAPI_ specification of the customers service, otherwise it can't be loaded by tooks like the _Swagger UI_.
=> Fix typo in customers service API specification

README.adoc, template.sh
Currently all the objects are being created under the current namespace (for me it was default).
`new-project` also sets the current project to it's argument.
=> Use new-project for dedicated portal

Gopkg.lock, Gopkg.toml, cmd/customers-webserver/cluster.go, cmd/customers-webserver/cluster_handler.go, cmd/customers-webserver/main.go
This is a work in progress PR to add a functional customers web server. It adds an endpoint to get a list of clusters. Right now it only contains hardcoded data
There's still a lot to be done. We need to decide on an API, connect it to the caching SQL server, to the message queues, figure out authentication, etc etc, but this is a good starting point.
=> Customers web server: implement /api/clusters (with mock data)

sandbox/prepare_vm.yml
This patch changes the sandbox installation scripts so that the `rsync` package is explicitly installed. It is usually already installed, but as we plan to use it from the `Jenkinsfile` it is better to make sure that
it is installed.
=> Add `rsync` to sandbox

sandbox/README.adoc
A recent change in the sandbox build script required
python jinja2 modules. Adding that to the requirements.
=> update sandbox readme to include new dependencies

sandbox/README.adoc
The package is needed for building the sandbox image in both _libvirt_ and _oVirt_, but it is currently only mentioned in the _libvirt instructions.
=> Add `python34-jinja2` to the oVirt instructions

cmd/customers-webserver/cluster_handler.go
Add length, page, and size to the response. I forgot these response values in the original PR, but they are specified in the acceptance criteria for the Jira card
=> customers webserver: Add length, page, and size to the response

build.py, images/messaging-service/Dockerfile, images/messaging-service/Downloads, images/messaging-service/setup.sh
Currently the _ActiveMQ_ tarball is downloaded by the build script, before building the container. The build script caches it in the `.downloads` directory in order to avoid downloading it repeatedly. But
this directory is not used in the continuous integration environments. For example, when building in Jenkins the tarball is downloaded everytime. To avoid that this patch moves the download to the build of the container. This way it will be cached as part of the container build caching process. The net result is a couple of minutes less in most builds, and a shorter build script.
=> Download ActiveMQ from container

images/messaging-service/setup.sh
The progress messages generated by the execution of `wget` are cluttering the build logs. This patch removes them.
=> Make 'wget' quiet

Jenkinsfile
This patch changes the _Jenkins_ pipeline of the project so it will send a notification to the _Slack_ channel when it fails.
=> Send slack notification when pipeline fails

build.py
Currently when the build fails in a function whose result is cached we generate a nested exception message. For example, if the `docker` command doesn't exist the error message is like this:
```
Running command 'docker build --tag=dedicated-portal/clusters-service:latest .'
Traceback (most recent call last):
File "./build.py", line 90, in helper
value = cache[key]
KeyError: ()
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "./build.py", line 90, in helper
value = cache[key]
KeyError: ('clusters-service',)
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "./build.py", line 694, in <module>
main()
File "./build.py", line 687, in main
argv.func()
File "./build.py", line …
```
=> Avoid nested exceptions due to cache in 'build.py'

images/messaging-service/Dockerfile, images/messaging-service/entrypoint.sh, images/messaging-service/etc/bootstrap.xml, images/messaging-service/etc/broker.xml, images/messaging-service/etc/jolokia-access.xml, images/messaging-service/etc/management.xml, images/messaging-service/setup.sh, template.yml
Currently the _ActiveMQ_ container has the management console. This patch enables it. The console will be available via the route for host name `messaging-console`. For example, if the domain selected is `example.com` then the console will be available in the following URL:
```
https://messaging-console.example.com/console/
```
The default user name and password are `admin` and `redhat123`.
=> Enable ActiveMQ console

build.py
Currently the `build.py` script creates a link to the `vendor` directory inside the Go source directory, because this was needed in a previous incarnation of the script that was used to build an application where it was necessary to generate Kubernetes client code. This is no longer needed, so this patch removes it.
=> Remove unneeded 'vendor' link

cmd/customers-service/main.go
panic, because the service is not useful without a database.
=> customers-service: report error when failing to connect to etcd

cmd/customers-service/main.go, cmd/customers-service/server.go, images/customers-service/Dockerfile, template.yml
Add a serve command to the customer service.
**Terminal dump**
Running server:
```
$GOBIN/customers-service serve
I0626 16:43:40.592917     756 server.go:91] Starting customers-service server at 0.0.0.0:8080.
```
Gloabl options:
```
$ $GOBIN/customers-service 
A tool that can service customers.
Usage:
customers-service [command]
Available Commands:
help        Help about any command
serve       Serve a customers service serrvice
Flags:
--alsologtostderr                  log to standard error as well as files
-h, --help                             help for customers-service
--log_backtrace_at traceLocation   when logging hits line file:N, emit a stack trace (default :0)
--log_dir string                   If non-empty, write log files in this directory
--logtostderr …
```
=> Add a serve command to the customer service

Gopkg.lock, Gopkg.toml, cmd/clusters-service/clusters_service.go, cmd/clusters-service/clusters_service_test.go, cmd/clusters-service/main.go, cmd/clusters-service/openapi.yaml, cmd/clusters-service/server.go, images/clusters-service/Dockerfile, images/clusters-service/migrations/1530102671_create_schema.down.sql, images/clusters-service/migrations/1530102671_create_schema.up.sql, images/clusters-service/migrations/1530102892_add_cluster_name.down.sql, images/clusters-service/migrations/1530102892_add_cluster_name.up.sql, pkg/sql/schema.go, pkg/sql/schema_test.go, template.yml
```
$ ./hack/cluster-restart.sh
$ curl  http://clusters-service.127.0.0.1.nip.io/clusters
{
"Page": 0,
"Size": 0,
"Total": 0,
"Items": []
}
$ $ for i in $( seq 1 5 ); do
>   curl -X POST -H "Content-Type: application/json" \
>     --data "{\"name\":\"mycluster${i}\"}" \
>     http://clusters-service.127.0.0.1.nip.io/clusters
> done
{
"Name": "mycluster1",
"UUID": "16vCmn3jcYxY4vywN0igFcOwoh6"
}
{
"Name": "mycluster2",
"UUID": "16vCmp6xOHimgYFeLEmdh8l2e85"
}
{
"Name": "mycluster3",
"UUID": "16vCmjzNIGq6fZKLdMU3rN6OSrR"
}
{
"Name": "mycluster4",
"UUID": "16vCmoOgUiWDskaNzrjLRGtw2dR"
}
{
"Name": "mycluster5",
"UUID": "16vCmoyyQnKiC7jgCwxJ4Gl5RTT"
}
$ oc  logs -c service  clusters-service-fc9b8db87-jcgvz 
Could not connect:  db.Ping: dial tcp [::1]:5432: connect: connection refused...
Could …
```
=> Add schema migrations & postgres implementation

cmd/customers-service/README.adoc, cmd/customers-service/server.go
This PR is the final step of the move from etcd to sql as a datastore for the customers service.
~~Depends on #61 , once README is merged I would like to update it with this change.~~
cc: @oourfali @jhernand @cben
=> customers-service: Switching from etcd to psql

cmd/clusters-service/server.go, cmd/customers-service/README.adoc, cmd/customers-service/server.go
Currently the URLs of the collections are directly in the root of the URL space:
```
/clusters
/customers
```
This complicates the sharing the URL space with other API services, and having multiple versions of the same API. To improve that this patch changes the URLs, introducing a common `api` prefix, a segment to
containing the name of the API, and a segment containing the version:
```
/api/clusters_mgmt/v1/clusters
/api/customers_mgmt/v1/customers
```
To avoid repeating this prefix in all the routes a new sub-router is introduced.
=> Add subrouters for the API prefix

Gopkg.lock, Gopkg.toml, cmd/clusters-service/clusters_service.go, cmd/clusters-service/server.go, cmd/customers-service/handlers.go, cmd/customers-service/server.go
Currently the services generate their own simple access logs, each using a different mechanism. This patch changes them so that they log all requests, and using the same mechanism.
=> Add access log handler

cmd/customers-service/handlers.go
`writeJSONResponse()` ignores errors from `json.Marshal()`.  The only error situations I see in [documentation](https://golang.org/pkg/encoding/json/#Marshal) are:
> Channel, complex, and function values cannot be encoded in JSON. Attempting to encode such a value causes Marshal to return an UnsupportedTypeError.
Not a big problem for us but indeed `payload interface{}` could contain anything and we could accidentaly put there unsupported types.
It's more a matter of principle — as a rule we should not ignore errors, or we're cheating ourselves of the value (and cost) of coding in a language without exceptions!
In cases we never expect the error to happen, we can use the "must" idiom — call the function `mustWriteJSONResponse`, have it `panic()` on error.
Here, I decided even if unlikely …
=> Don't ignore error in writeJSONResponse()

.gitignore, Makefile
This patch removes references to the `.gopath` directory that was used by the `build.py` script.
=> Remove `build.py` leftovers

Jenkinsfile
After removing the `build.py` script it isn't possible to build the Go parts of the project outside of the directory pointed by the `GOPATH` environment variable, and the Jenkins build is failing. To solve that
this patch changes the `Jenkinsfile` so that `GOPATH` points to the workspace, and so that the source code is checked out in the subdirectory that the Go tools expect.
=> Fix Go environment in Jenkinsfile

cmd/customers-service/customers_service.go, cmd/customers-service/server.go, cmd/customers-service/sql_customers_service.go
Return error upon `Close` method - such that `Service` and `Server` would implement `io.Closer` interface. 
cc: @cben @jhernand
=> customers-service: Return an error on Close

template.yml
As continuation of removing etcd and adding psql - remove etcd pod and add psql as container in `customers-service` pod, similar to `clusters-service`.
cc: @cben @jhernand @yaacov
=> customers-service: Removing etcd from template and adding psql

cmd/customers-service/handlers.go, cmd/customers-service/sql_customers_service_test.go
Currently it is **theoretically** possible for an attacker to crash the service using crafted request.
**What happen**
An attacker creating a request that will get into line 101 will crash the server.
**What we want**
An attacker creating a malicious request will be logged, but not crash the service.
=> Do not crash on user input while serving http request

cmd/customers-service/handlers.go
Fix typo from https://github.com/container-mgmt/dedicated-portal/pull/83
`err == nil` should be `err != nil`
=> Fix err eq nil typo

cmd/clusters-service/README.adoc, cmd/clusters-service/clusters_service.go, cmd/clusters-service/handlers.go, images/clusters-service/migrations/1530102892_add_cluster_details.down.sql, images/clusters-service/migrations/1530102892_add_cluster_details.up.sql, images/clusters-service/migrations/1530102892_add_cluster_name.down.sql, images/clusters-service/migrations/1530102892_add_cluster_name.up.sql
This PR updates the service API to include more details: nodes, memory, CPU, storage
Creation allows specifying total required resources.
Get will allow seeing the total and used resource.
At the moment, only total resource availability is implemented, as we still need to get the dynamic data (in a follow-up PR).
Also added service README with usage examples.
=> API to retrieve cluster details

cmd/clusters-service/handlers.go
**Desccription**
In cluster service we usually return a json with some `error` string in case of internal error.
In the case of create  cluster we return empty string.
This PR return the error to the client in json form.
=> Return the error creating cluster to the user

Jenkinsfile, template.sh
Currently the `template.sh` script and the `Jenkinsfile` try to create the `dedicated-portal` project if it doesn't exist. But if the project already exists, and it isn't the current one, they don't make it the
current one, and as a result the objects may be created in other namespace. This patch changes both files so that if the creation of the project fails (because it already exists, most probably) they try to
make it the current one explicitly.
=> Always change to the `dedicated-portal` project

cmd/customers-service/handlers.go, cmd/customers-service/server.go, cmd/customers-service/service/sql_customers_service.go, pkg/auth/auth.go
Currently we only check that the token is valid.
This PR adds check that the token subject match the request user id.
**Terminal dump**
Bad user ID
``` bash
$ curl -s http://localhost:8000/api/customers_mgmt/v1/customers/BAD_USER_ID -H "authorization: Bearer $TOKEN"| jq
{
"error": "user id does not match token"
}
```
Currect user ID
[ I do not have a postgres server running -  pq: Ident authentication failed for user \"postgres\"]
``` bash
$ curl -s http://localhost:8000/api/customers_mgmt/v1/customers/924fea...2f0b -H "authorization: Bearer $TOKEN"| jq
{
"error": "Error getting customer, pq: Ident authentication failed for user \"postgres\""
}
```
=> Check user id before answering requests

hack/cluster-restart.sh
A small tweak to allow running `hack/cluster-restart.sh` from any working directory.
=> hack/cluster-restart.sh: Don't require running from project root

cmd/clusters-service/clusters_service.go, cmd/clusters-service/handlers.go, cmd/customers-service/handlers.go, cmd/customers-service/service/customers_service.go, cmd/customers-service/service/demo_customers_service.go, cmd/customers-service/service/sql_customers_service.go, pkg/api/cluster_types.go, pkg/api/customer_types.go, pkg/api/doc.go
Currently the types used in the API are defined in the same packages where the servers are implemented. This makes it easy to hink that those types can be tweaked to make life simpler for the implementations of the servers. To avoid that this patch moves them to a new `api` package, so it is clearer that these types are part of the contract of the services, and that they need to be kept stable and backwards compatible.
=> Move API types to `api` package

.travis.yml, Gopkg.lock, Gopkg.toml, cmd/clusters-service/README.adoc, cmd/clusters-service/cluster_provisioner.go, cmd/clusters-service/clusters_service.go, cmd/clusters-service/server.go
This is a **work in progress** pushed for transparency purposes.
~~Adds ClusterDeployment struct~~ Allowing cluster-service to create a k8s custom resource ClusterDeployment struct which will then be used by CO to create actual machines.
Todo:
cc: @jhernand @cben  @oourfali
=> Adding ClusterDeployment using cluster-operator

cmd/clusters-service/server.go, cmd/customers-service/server.go
Currently all the places where we need to specify the name of an HTTP method repeat the corresponding `GET` or `POST` string. This patch changes all those places to use the `MethodGet` and `MethodPost` constants defined in the `http` package.
=> Use `http.MethodGet` instead of `GET` string

cmd/clusters-service/clusters_service.go, cmd/clusters-service/handlers.go, cmd/clusters-service/openapi.yaml, cmd/clusters-service/server.go, images/clusters-service/migrations/1530102671_create_schema.up.sql, pkg/api/cluster_types.go
In general the name of the field/columns for primary keys should be `id`, regardless of what is the mechanism that is used to generate it.
=> Rename cluster `UUID` to `ID`

cmd/clusters-service/cluster_provisioner.go
`ClusterVersion` object is missing some fields which prevent CO from provisioning clusters properly - These fields are hardcoded *on purpose*.
cc: @cben @zgalor @jhernand
=> cluster-service: Fix missing fields in ClusterVersion

cmd/clusters-service/README.adoc, cmd/clusters-service/clusters_service.go, cmd/clusters-service/data/migrations/1530102892_add_cluster_details.down.sql, cmd/clusters-service/data/migrations/1530102892_add_cluster_details.up.sql, pkg/api/cluster_types.go
Add the field to the DB, and the API.
When a cluster is created the state is set to "Installing".
Currently this is not changed.
Status should be dynamically updated in the future.
=> Add State field to Cluster API type

cmd/clusters-service/README.adoc, cmd/clusters-service/clusters_service.go, cmd/clusters-service/handlers.go
This parameter is true by default.
If false the cluster will be created in the DB but not provisioned.
This can be used to sync with externally provisioned clusters.
=> Add `provision` parameter to cluster creation API

cmd/clusters-service/cluster_provisioner.go
Currently the specification of the cluster version used with the cluster operator specifies that images should never be pulled. This is OK for development environments, where the images are pulled manually, but it is not OK for production environments. This patch changes the specification of the cluster version so that images are pulled if not present.
=> Pull cluster operator images if not present

cmd/clusters-service/cluster_provisioner.go
This patch changes the clusters provisioner so that it uses the pre-built images published by the project.
=> Use pre-built cluster operator images

cmd/clusters-service/cluster_provisioner.go, template.yml
Changes our deployment namespace from `dedicated-portal` to `unified-hybrid-cloud`.
cc: @jhernand @cben @yaacov @zgalor
=> change the name of the namespace

cmd/clusters-service/server.go, cmd/customers-service/server.go, template.sh, template.yml
Currently each service use different routing scheme, thie PR makes both use `edge` routing.
**Example**
Running the services in demo mode on local machine:
```
TEMPLATE_DEMO_MODE=--demo-mode ./hack/cluster-restart.sh
```
Routing table:
```
$ oc get route
NAME                HOST/PORT                            PATH      SERVICES            PORT      TERMINATION   WILDCARD
clusters-service    clusters-service.127.0.0.1.nip.io              clusters-service    <all>     edge          None
customers-service   customers-service.127.0.0.1.nip.io             customers-service   <all>     edge          None
```
Testing response:
```
curl -k https://customers-service.127.0.0.1.nip.io
curl -k https://clusters-service.127.0.0.1.nip.io
```
=> All services use same convention

images/clusters-service/Dockerfile, template.yml
Currently the database of the clusters service runs as a container inside the same pod that runs the service itself.
=> Use DB as a service

Jenkinsfile, README.adoc, template.sh, template.yml
Rename "dedicated-portal" to "unified-hybrid-cloud" (our new project name) in the resources we create on our various deployments. (Jenkins, oc template etc.)
Building on top of work done in #131 
cc: @jhernand @zgalor @yaacov @cben
=> Rename "dedicated-portal" to "uhc"

Gopkg.lock, Gopkg.toml, cmd/clusters-service/README.adoc, cmd/clusters-service/cluster_provisioner.go, cmd/clusters-service/clusters_service.go, cmd/clusters-service/handlers.go, cmd/clusters-service/server.go, pkg/api/cluster_types.go, template.yml
Add `.../clusters/{id}/status` endpoint to get the cluster status.
Added a label "ID" with the cluster id in the `clusterdeployment`
This ID is used to find the cluster when status is requested.
Another important change: first create the cluster in the DB, and then try provisioning it if required.
Also add ClusterRole and ClusterRoleBinding creation in template.yml to allow the uhc sa to access clusteroperator CRDs
Future related tasks (external to this PR):
[Update the DB whenever the status changes](https://jira.coreos.com/browse/SDA-127)
[Generate unique name for clusterdeployment](https://jira.coreos.com/browse/SDA-128)
[Get more specific details on status endpoint](https://jira.coreos.com/browse/SDA-129)
=> Add API endpoint to get cluster status
